name: fetch
on:
  schedule:
    - cron:  '0 8 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl 'https://amazon-price-tracker-two.vercel.app/api/products/refresh'